### ISSUE TITLE
make create-python-client generates a python client incompatible with python 3.7

### ISSUE THREAD

**Issue by carbonin** [filanov/bm-inventory#522]
After generating the client and trying to use it with python 3.7 I get the following error:
```
Traceback (most recent call last):
  File "./bm_inventory_api.py", line 4, in <module>
    from bm_inventory_client import ApiClient, Configuration, api, models
  File "/home/ncarboni/.local/lib/python3.7/site-packages/bm_inventory_client/__init__.py", line 19, in <module>
    from bm_inventory_client.api.events_api import EventsApi
  File "/home/ncarboni/.local/lib/python3.7/site-packages/bm_inventory_client/api/__init__.py", line 6, in <module>
    from bm_inventory_client.api.events_api import EventsApi
  File "/home/ncarboni/.local/lib/python3.7/site-packages/bm_inventory_client/api/events_api.py", line 127
    async=params.get('async'),
        ^
SyntaxError: invalid syntax
```

We are hitting this bug https://github.com/swagger-api/swagger-codegen/issues/8328
I think the version of codegen we use to create the client should be updated.

**Comment by carbonin** [comment]
https://github.com/jimschubert/swagger-codegen-cli.docker is archived and no longer maintained so I would suggest we move to a different image to get this fixed.

I'll take a look at using https://github.com/OpenAPITools/openapi-generator#16---docker

**Comment by romfreiman** [comment]
That's why you should use skipper

**Comment by carbonin** [comment]
The error is the same regardless.

The image we're using to generate the client package has a bug and needs to be updated. This has nothing to do with skipper as far as I can tell.

**Comment by filanov** [comment]
@tsorya
